version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgredb


  postgredb:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
      POSTGRES_DB: seracell_demo
    ports:
      - "5432:5432"

  redis_demo:
    image: "redis"
    ports:
      - "6379:6379"
    