version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: seracell_demo_db
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    